ruby '2.2.0'
source 'https://rubygems.org'
gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml'
gem 'bootstrap-sass'
gem 'jquery-ui-rails'
gem 'font-awesome-rails'
gem 'pg'
group :development, :test do
	gem 'sqlite3'
	gem 'html2haml'
    gem 'byebug'
    gem 'web-console', '~> 2.0'
    gem 'spring'
end
